name: Convert JMeter HTML to CSV

on: push
jobs:
  convert-html-to-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JMeter Plugins CMD
        run: |
          wget https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2/cmdrunner-2.2.jar -O cmdrunner.jar
          wget https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-cmd/2.2/jmeter-plugins-cmd-2.2.jar -O jmeter-plugins-cmd.jar

      - name: Convert JMeter HTML to CSV
        run: java -cp cmdrunner.jar:jmeter-plugins-cmd.jar kg.apc.cmd.UniversalConverter \
             --tool Reporter --plugin-type CompositeResultCollector --generate-csv output.csv \
             -i results.html

      - name: Display converted CSV
        run: cat output.csv
