name: Convert JTL to CSV

on: push
 
jobs:
  convert-jtl-to-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Convert JTL to CSV
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/jmeter \
            -w /jmeter \
            justb4/jmeter \
            -g result.jtl -o Jmeter_results.csv

      - name: Display converted CSV
        run: cat Jmeter_results.csv
