name: Convert JTL to CSV

on: push
 
jobs:
  convert-jtl-to-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Download JMeter Plugins CMD
        run: |
          wget https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2/cmdrunner-2.2.jar -O cmdrunner.jar
          wget https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-cmd/2.2/jmeter-plugins-cmd-2.2.jar -O jmeter-plugins-cmd.jar

      - name: Convert JTL to CSV
        run: java -cp cmdrunner.jar;jmeter-plugins-cmd.jar kg.apc.cmd.UniversalConverter --tool Reporter --input-jtl result.jtl --plugin-type AggregateReport --generate-csv converted_results.csv 2>&1 | tee conversion_log.txt
      - name: Upload CSV file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: converted-results
          path: converted_results.csv
