name: Convert JMeter HTML to CSV

on: push
 

jobs:
  convert-html-to-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Convert JMeter HTML to CSV
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/jmeter \
            -w /jmeter \
            justb4/jmeter-plugins-cmd \
            --tool Reporter --plugin-type CompositeResultCollector --generate-csv output.csv \
            -i results.html

      - name: Display converted CSV
        run: cat output.csv
