name: Convert JTL to CSV

on: push
 
jobs:
  convert-jtl-to-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Convert JTL to CSV
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/jmeter \
            -w /jmeter \
            justb4/jmeter \
            -g result.jtl -o converted_results.csv 2>&1 | tee conversion_log.txt

      - name: Display conversion log
        run: cat conversion_log.txt
