name: Convert JTL to CSV and Upload Artifact

on: push
 

jobs:
  convert-jtl-to-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JMeter
        run: |
          wget -q https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.3.tgz
          tar -xf apache-jmeter-5.4.3.tgz
          export PATH=$PATH:$GITHUB_WORKSPACE/apache-jmeter-5.4.3/bin

      - name: Display JMeter version
        run: jmeter --version

      - name: Convert JTL to CSV
        run: |
          /jmeter/apache-jmeter-5.4.3/bin/jmeter -g result.jtl -o /jmeter/output 2>&1 | tee -a conversion_log.txt

      - name: Change ownership of converted CSV file
        run: sudo chown $USER:$USER /jmeter/output/*

      - name: Display working directory contents
        run: ls -l /jmeter/output

      - name: Display last lines of conversion log
        run: tail -n 20 conversion_log.txt

      - name: Upload converted CSV files as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: converted-results
          path: /jmeter/output
