name: Convert JTL to CSV and Upload Artifact

on: push
  

jobs:
  convert-jtl-to-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Convert JTL to CSV
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/jmeter \
            -w /jmeter \
            -e JMETER_CMD=AggregateReport \
            apache/jmeter:latest -g result.jtl -o /jmeter/output 2>&1 | tee -a conversion_log.txt

      

      - name: Display working directory contents
        run: ls -l

      - name: Display last lines of conversion log
        run: tail -n 20 conversion_log.txt

      - name: Upload converted CSV files as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: converted-results
          path: /jmeter/output
