name: Run workflow in single job
on: push 
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
    - name: Get a code
      uses: actions/checkout@v3
    - name: istalling node package
      uses: actions/setup-node@v3
      with:
         node-version: '18'
    - name: npm istalled
      run: npm ci
    - name: Run lint
      run: npm run lint
    - name: Run test
      run: npm run test
    - name: npm deploy
      run: npm run build
